# Generated by Django 3.1.4 on 2020-12-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201226_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='material',
            field=models.TextField(),
        ),
    ]
