# Generated by Django 3.1.6 on 2021-03-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_id',
            field=models.CharField(choices=[('Arushi', '1'), ('Others', '2')], default='1', max_length=130),
        ),
    ]
